# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-01-07T17:36:28Z"
  labels:
    app: njs1
  name: njs1
spec:
  containers:
  - args:
    - nginx
    - -c
    - /etc/nginx/njshello.nginx.conf
    image: localhost/editorbank/njshello:latest
    name: njs1
    ports:
    - containerPort: 80
      hostPort: 8500
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
